service: backend
frameworkVersion: '3'
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

